-- MySQL Script generated by MySQL Workbench
-- Mon Oct 13 10:23:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema concessionaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema concessionaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concessionaria` DEFAULT CHARACTER SET utf8 ;
USE `concessionaria` ;

-- -----------------------------------------------------
-- Table `concessionaria`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`clientes` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(100) NULL,
  `cpf_cliente` CHAR(11) NULL,
  `email_cliente` VARCHAR(100) NULL,
  `telefone_cliente` VARCHAR(20) NULL,
  `dat_nasc_cliente` DATE NULL,
  PRIMARY KEY (`id_clientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(100) NULL,
  `telefone_funcionario` VARCHAR(20) NULL,
  `email_funcionario` VARCHAR(100) NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`marca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `nome_marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`modelo` (
  `id_modelo` INT NOT NULL AUTO_INCREMENT,
  `ano_modelo` YEAR NULL,
  `cor_modelo` VARCHAR(20) NULL,
  `nome_modelo` VARCHAR(45) NULL,
  `tipo_modelo` VARCHAR(45) NULL,
  `marca_id_marca` INT NOT NULL,
  PRIMARY KEY (`id_modelo`, `marca_id_marca`),
  INDEX `fk_modelo_marca1_idx` (`marca_id_marca` ASC),
  CONSTRAINT `fk_modelo_marca1`
    FOREIGN KEY (`marca_id_marca`)
    REFERENCES `concessionaria`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`vendas` (
  `id_vendas` INT NOT NULL AUTO_INCREMENT,
  `data_venda` VARCHAR(45) NULL,
  `valor_venda` DECIMAL(10,2) NULL,
  `clientes_id_clientes` INT NOT NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  `modelo_id_modelo` INT NOT NULL,
  PRIMARY KEY (`id_vendas`, `clientes_id_clientes`, `funcionario_id_funcionario`, `modelo_id_modelo`),
  INDEX `fk_vendas_clientes_idx` (`clientes_id_clientes` ASC) ,
  INDEX `fk_vendas_funcionario1_idx` (`funcionario_id_funcionario` ASC) ,
  INDEX `fk_vendas_modelo1_idx` (`modelo_id_modelo` ASC) ,
  CONSTRAINT `fk_vendas_clientes`
    FOREIGN KEY (`clientes_id_clientes`)
    REFERENCES `concessionaria`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `concessionaria`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_modelo1`
    FOREIGN KEY (`modelo_id_modelo`)
    REFERENCES `concessionaria`.`modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
